all:
	-gcc hw0201.c -Wall -Wextra -o hw0201
	-gcc hw0202.c -Wall -Wextra -o hw0202
	-gcc hw0203.c -Wall -Wextra -o hw0203
	-gcc hw0205.c -Wall -Wextra -o hw0205

clean:
	-rm -f hw0201 hw0202 hw0203 hw0205
