all:
	-gcc hw0101.c -Wall -Wextra -o hw0101
	-gcc hw0102.c -Wall -Wextra -o hw0102
	-gcc hw0103.c -Wall -Wextra -o hw0103
	-gcc hw0104.c -Wall -Wextra -o hw0104
	-gcc hw0105.c -Wall -Wextra -o hw0105
clean:
	rm hw0101 hw0102 hw0103 hw0104 hw0105
